import {useEffect,useRef,useState,type PointerEvent} from 'react';
import ScienceRange from '../../components/ScienceRange';
import ScienceQuiz from '../../exercises/ScienceQuiz';
import {engine,ramp,limit,G} from './physics';
import './energy.css';
const f=(n:number)=>n.toLocaleString('he-IL',{maximumFractionDigits:2});
function Bars({items,total}:{items:{label:string,value:number,color:string}[];total:number}){return <div className="energy-bars">{items.map(i=><div key={i.label}><span>{i.label} <bdi>{f(i.value)} J</bdi></span><div className="energy-bar"><i style={{width:total?100*i.value/total+'%':'0%',background:i.color}}/></div></div>)}</div>}
export default function EnergyLabs(){
const [tab,setTab]=useState<'ramp'|'steam'>('ramp');
return <><section className="intro"><div><div className="eyebrow">אנרגיה / מעבדה פעילה</div><h1>אנרגיה משנה צורה</h1><p>גוררים, משנים ורואים את המספרים בתוך הנוסחאות.</p></div></section><div className="energy-tabs" role="group" aria-label="בחירת מעבדת אנרגיה"><button aria-pressed={tab==='ramp'} onClick={()=>setTab('ramp')}>גובה ↔ תנועה</button><button aria-pressed={tab==='steam'} onClick={()=>setTab('steam')}>קיטור: חום → תנועה</button></div>{tab==='ramp'?<Ramp/>:<Steam/>}</>;
}
function Ramp(){
const [mass,setMass]=useState(10),[height,setHeight]=useState(5),[u,setU]=useState(0),[direction,setDirection]=useState(1),[playing,setPlaying]=useState(false);
const drag=useRef<number|null>(null),model=ramp(mass,height,1-u*u),x=110+u*u*520,y=70+u*u*300;
useEffect(()=>{if(!playing)return;let last=performance.now(),id=0;const frame=(now:number)=>{const dt=Math.min((now-last)/1000,.05);last=now;setU(v=>limit(v+direction*dt/model.duration,0,1));id=requestAnimationFrame(frame)};id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id)},[playing,direction,model.duration]);
useEffect(()=>{if((direction===1&&u>=1)||(direction===-1&&u<=0))setPlaying(false)},[u,direction]);
const move=(e:PointerEvent<SVGSVGElement>)=>{const m=e.currentTarget.getScreenCTM();if(!m)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());setU(Math.sqrt(limit(((p.x-110)*520+(p.y-70)*300)/(520**2+300**2),0,1)))};
const finish=(e:PointerEvent<SVGSVGElement>)=>{drag.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)};
return <><div className="astro-workspace"><aside className="panel astro-lesson"><div className="eyebrow">מסילה חלקה · ללא חיכוך</div><h2>גובה הופך למהירות</h2><p>בירידה, אנרגיית הגובה קטנה ואנרגיית התנועה גדלה. בעלייה קורה ההפך. סכום שתי האנרגיות נשמר.</p><Bars total={model.total} items={[{label:'אנרגיית גובה',value:model.potential,color:'#b176dc'},{label:'אנרגיית תנועה',value:model.kinetic,color:'#149ba0'}]}/><p><strong>סך הכול: {f(model.total)} J</strong></p><p>גובה האפס הוא תחתית המסילה. הגוף מחליק ללא סיבוב; זווית המסילה 30°.</p></aside>
<section className="panel astro-sim"><div className="sim-toolbar"><strong>גררו את הגוף לאורך המסילה</strong><button className="reset" onClick={()=>{setPlaying(false);setU(0)}}>↻ לראש המסילה</button></div><svg viewBox="0 0 740 435" className="energy-diagram" role="group" aria-label="מסילה עם גוף נגרר" onPointerDown={e=>{if(e.button!==0||drag.current!==null||!(e.target instanceof Element)||!e.target.closest('[data-body]'))return;e.preventDefault();drag.current=e.pointerId;setPlaying(false);e.currentTarget.setPointerCapture(e.pointerId);move(e)}} onPointerMove={e=>{if(drag.current===e.pointerId)move(e)}} onPointerUp={finish} onPointerCancel={finish} onLostPointerCapture={()=>{drag.current=null}}>
<rect width="740" height="435" fill="#edf5f7"/><path d="M110 70 L630 370 L110 370 Z" fill="#dce7eb"/><path d="M110 70 L630 370" stroke="#405c6f" strokeWidth="7" fill="none"/><line x1="65" x2="690" y1="370" y2="370" stroke="#9bafb9" strokeDasharray="6 5"/><line x1={x} x2={x} y1={y} y2="370" stroke="#b176dc" strokeWidth="3" strokeDasharray="5 5"/>
<text x="390" y="38" textAnchor="middle">מהירות: {f(model.speed)} מ׳/שנייה</text><text x="370" y="411" textAnchor="middle">h = 0 · תחתית המסילה</text><text x="85" y="215" textAnchor="middle" transform="rotate(-90 85 215)">גובה התחלתי: {f(height)} מ׳</text>
<g data-body="" role="slider" tabIndex={0} aria-label="גובה הגוף על המסילה" aria-valuemin={0} aria-valuemax={height} aria-valuenow={model.h} onKeyDown={e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();setPlaying(false);setU(Math.sqrt(1-limit(model.h/height+(['ArrowUp','ArrowLeft'].includes(e.key)?.02:-.02),0,1)))}}} className="energy-grip"><circle cx={x} cy={y} r="27" fill="transparent"/><circle cx={x} cy={y} r="18" fill="#eaaa4c" stroke="#fff" strokeWidth="3"/></g></svg><div className="astro-playbar"><button className="primary-button" onClick={()=>{setDirection(1);if(u===1)setU(0);setPlaying(true)}}>שחרור בירידה</button><button className="subtle-button" onClick={()=>{setDirection(-1);setU(1);setPlaying(true)}}>תנועה בעלייה</button><button className="subtle-button" disabled={!playing} onClick={()=>setPlaying(false)}>השהיה</button></div><p className="interaction-note">״תנועה בעלייה״ מתחילה בתחתית במהירות הדרושה להגיע לגובה ההתחלתי. ההרצה נעצרת בקצה; האנרגיה ברגע שלפני העצירה מוצגת. גרירה בוחרת מצב בניסוי.</p></section></div>
<section className="panel astro-controls energy-controls"><ScienceRange label="מסת הגוף" value={mass} min={1} max={100} unit="ק״ג" onChange={v=>{setPlaying(false);setMass(v)}}/><ScienceRange label="גובה התחלתי" value={height} min={1} max={20} step={.1} unit="מ׳" onChange={v=>{setPlaying(false);setHeight(v);setU(0)}}/><ScienceRange label="גובה הגוף כעת" value={model.h} min={0} max={height} step={.01} unit="מ׳" onChange={v=>{setPlaying(false);setU(Math.sqrt(1-v/height))}}/></section>
<section className="panel jeans-lesson"><h2>הנוסחאות מתעדכנות בזמן אמת</h2><div className="energy-equations"><article><h3>אנרגיית גובה</h3><p dir="ltr">Eₚ = mgh</p><p dir="ltr">{f(mass)} × {G} × {f(model.h)} = {f(model.potential)} J</p></article><article><h3>אנרגיית תנועה</h3><p dir="ltr">Eₖ = ½mv²</p><p dir="ltr">½ × {f(mass)} × {f(model.speed)}² = {f(model.kinetic)} J</p></article><article><h3>שימור אנרגיה</h3><p dir="ltr">Eₚ + Eₖ = mgH</p><p dir="ltr">{f(model.potential)} + {f(model.kinetic)} = {f(model.total)} J</p></article></div><p><bdi>m</bdi> מסה בק״ג, <bdi>h</bdi> גובה במטרים, <bdi>v</bdi> מהירות במ׳/שנייה, <bdi>g = 9.81 m/s²</bdi>. המספרים המוצגים מעוגלים; החישוב משתמש בדיוק מלא.</p><h3>נסו בעצמכם</h3><p>מצאו את הגובה שבו אנרגיית הגובה ואנרגיית התנועה שוות. אחר כך הכפילו את המסה: האם המהירות באותו גובה השתנתה?</p><p><a href="https://phet.colorado.edu/sims/html/energy-skate-park/latest/energy-skate-park_en.html" target="_blank" rel="noreferrer">להרחבה: מדמה Energy Skate Park של PhET ↗</a></p></section>
<ScienceQuiz questions={[{question:'בחצי הגובה ההתחלתי, ללא חיכוך, איך מתחלקת האנרגיה?',options:['חצי אנרגיית גובה וחצי אנרגיית תנועה','הכול אנרגיית תנועה','אין מספיק מידע'],answer:0,explanation:'Eₚ = mgH/2, והשאר הוא Eₖ = mgH/2.'},{question:'הכפלנו את המסה. מה קורה למהירות באותו גובה?',options:['מוכפלת','אינה משתנה','קטנה בחצי'],answer:1,explanation:'v = √(2g(H−h)); המסה מצטמצמת ממשוואת שימור האנרגיה.'},{question:'בעלייה חופשית על המסילה, איזו המרה מתרחשת?',options:['גובה לתנועה','תנועה לגובה','חום למסה'],answer:1,explanation:'המהירות קטנה והגובה גדל, תוך שימור האנרגיה המכנית.'}]}/></>;
}
function Steam(){
const [power,setPower]=useState(1),[hot,setHot]=useState(200),[cold,setCold]=useState(20),[quality,setQuality]=useState(50),[inertia,setInertia]=useState(10),[time,setTime]=useState(0),[playing,setPlaying]=useState(false);
const e=engine(power*1000,time,hot,cold,quality/100,inertia),angle=e.angle*180/Math.PI;
useEffect(()=>{if(!playing)return;let last=performance.now(),id=0;const frame=(now:number)=>{const dt=Math.min(.05,(now-last)/1000);last=now;setTime(v=>Math.min(10,v+dt));id=requestAnimationFrame(frame)};id=requestAnimationFrame(frame);return()=>cancelAnimationFrame(id)},[playing]);
useEffect(()=>{if(time>=10)setPlaying(false)},[time]);
const change=(fn:()=>void)=>{setPlaying(false);setTime(0);fn()};
return <><div className="astro-workspace"><aside className="panel astro-lesson"><div className="eyebrow">מנוע חום סכמטי</div><h2>מהקיטור אל הגלגל</h2><p>מקור חם מחמם מים ויוצר קיטור. הקיטור מתפשט ומניע מנוע. חלק מהחום הופך לעבודה, והשאר נפלט למקור קר.</p><Bars total={e.heat} items={[{label:'עבודה → תנועה',value:e.work,color:'#149ba0'},{label:'חום שנפלט',value:e.rejected,color:'#db8550'}]}/><p><strong>חום שנכנס: {f(e.heat)} J</strong></p><p>נצילות בפועל: {f(e.efficiency*100)}%. גבול קרנו בטמפרטורות אלה: {f(e.carnot*100)}%.</p></aside><section className="panel astro-sim"><div className="sim-toolbar"><strong>דוד → מנוע → גלגל תנופה</strong><button className="reset" onClick={()=>{setPlaying(false);setTime(0)}}>↻ איפוס זמן</button></div>
<svg viewBox="0 0 740 435" className="energy-diagram" role="img" aria-label="קיטור מעביר חום למנוע שמסובב גלגל תנופה"><rect width="740" height="435" fill="#edf5f7"/><path d="M170 170 V90 H375 V170" fill="none" stroke="#dc8a52" strokeWidth="15"/><path d="M375 250 V345 H170 V270" fill="none" stroke="#5b9db7" strokeWidth="13"/><rect x="90" y="165" width="160" height="125" rx="25" fill="#bfd9e1" stroke="#547789" strokeWidth="3"/><path d="M105 236 Q140 226 175 236 T235 236 V269 Q235 276 225 276 H115 Q105 276 105 269Z" fill="#69b9d1"/><text x="170" y="210" textAnchor="middle">דוד קיטור</text><text x="170" y="323" textAnchor="middle">{hot}°C · מקור חם</text><text x="275" y="70" textAnchor="middle">חום נכנס: {f(power)} kW →</text><rect x="320" y="162" width="110" height="98" rx="12" fill="#597e8f"/><text x="375" y="213" textAnchor="middle" fill="white">מנוע</text><line x1="430" y1="210" x2="560" y2="210" stroke="#6a8290" strokeWidth="9"/><g transform={'translate(570 210) rotate('+angle+')'}><circle r="78" fill="#e3f0ed" stroke="#087d7c" strokeWidth="9"/>{[0,60,120].map(a=><line key={a} x1="-72" x2="72" y1="0" y2="0" transform={'rotate('+a+')'} stroke="#2b8888" strokeWidth="5"/>)}<circle cx="0" cy="-62" r="8" fill="#e3a94b"/></g><text x="570" y="323" textAnchor="middle">גלגל תנופה</text><text x="370" y="390" textAnchor="middle">מעבה / מקור קר: {cold}°C · חום נפלט</text></svg>
<div className="astro-playbar"><button className="primary-button" onClick={()=>{if(time>=10)setTime(0);setPlaying(v=>!v)}}>{playing?'השהיה':'הפעלת המנוע'}</button><span>זמן: {f(time)} שניות · מהירות זוויתית: {f(e.omega)} רדיאן/שנייה</span></div></section></div>
<section className="panel astro-controls energy-controls"><ScienceRange label="הספק חום נכנס" value={power} min={.1} max={5} step={.1} unit="kW" onChange={v=>change(()=>setPower(v))}/><ScienceRange label="טמפרטורת המקור החם" value={hot} min={120} max={400} unit="°C" onChange={v=>change(()=>setHot(v))}/><ScienceRange label="טמפרטורת המקור הקר" value={cold} min={5} max={80} unit="°C" onChange={v=>change(()=>setCold(v))}/><ScienceRange label="נצילות ביחס לגבול קרנו" value={quality} min={10} max={80} unit="%" onChange={v=>change(()=>setQuality(v))}/><ScienceRange label="מומנט התמד של הגלגל" value={inertia} min={1} max={50} unit="ק״ג·מ״ר" onChange={v=>change(()=>setInertia(v))}/><ScienceRange label="זמן חימום והנעה" value={time} min={0} max={10} step={.01} unit="שניות" onChange={v=>{setPlaying(false);setTime(v)}}/></section>
<section className="panel jeans-lesson"><h2>לא כל החום הופך לתנועה</h2><div className="energy-equations"><article><h3>חום שסופק</h3><p dir="ltr">Qᵢₙ = P × t</p><p dir="ltr">{f(power*1000)} × {f(time)} = {f(e.heat)} J</p></article><article><h3>עבודה מכנית</h3><p dir="ltr">W = ηQᵢₙ</p><p dir="ltr">{f(e.efficiency)} × {f(e.heat)} ≈ {f(e.work)} J</p></article><article><h3>מאזן אנרגיה</h3><p dir="ltr">Qᵢₙ = W + Qₒᵤₜ</p><p dir="ltr">{f(e.heat)} = {f(e.work)} + {f(e.rejected)} J</p></article><article><h3>אנרגיית תנועה סיבובית</h3><p dir="ltr">Eᵣₒₜ = ½Iω² = W</p><p dir="ltr">½ × {f(inertia)} × {f(e.omega)}² ≈ {f(e.work)} J</p></article></div><p><bdi>η</bdi> נצילות, <bdi>I</bdi> מומנט התמד (התנגדות לשינוי בסיבוב), <bdi>ω</bdi> מהירות זוויתית. כמו ש־<bdi>½mv²</bdi> מתאר תנועה בקו ישר, <bdi>½Iω²</bdi> מתאר סיבוב.</p><div className="formula normalized" dir="ltr"><span>ηₘₐₓ = 1 − T𝚌 / Tₕ</span><span>= 1 − {f(cold+273.15)} / {f(hot+273.15)}</span><span>= {f(e.carnot*100)}%</span></div><p>בנוסחת קרנו הטמפרטורות בקלווין: מוסיפים 273.15 לטמפרטורה בצלזיוס. במודל הנצילות בפועל היא {quality}% מגבול קרנו, ולא {quality}% מהחום הנכנס.</p><h3>נסו בעצמכם</h3><p>בחרו זמן של 5 שניות ורשמו את אנרגיית התנועה. העבירו ל־10 שניות: האם האנרגיה הוכפלה? האם מהירות הסיבוב הוכפלה או גדלה פי √2?</p></section>
<details className="model-notes panel"><summary>הנחות המודל: מה בדיוק מחושב?</summary><p>זהו מודל ממוצע של מנוע חום במצב פעולה, ולא סימולציית רתיחה או מחזור קיטור מפורט. המאגרים נשארים בטמפרטורות קבועות. אין חישוב לחץ, נפח, חום כמוס, משאבה או זמן חימום ראשוני. נצילות המנוע נבחרת כחלק מגבול קרנו; זו אינה תחזית נצילות של מנוע קיטור מסוים.</p><p>כל העבודה נטו נאגרת כאן בגלגל שמתחיל ממנוחה, ללא עומס חיצוני וללא חיכוך בציר. לכן הוא מאיץ. מנוע במכונה אמיתית מעביר בדרך כלל עבודה לעומס. הציור סכמטי; שינוי פרמטר מאפס את הזמן כדי להתחיל ניסוי חדש.</p><p><a href="https://openstax.org/books/physics/pages/12-4-applications-of-thermodynamics-heat-engines-heat-pumps-and-refrigerators" target="_blank" rel="noreferrer">מנועי חום ומאזן האנרגיה: OpenStax ↗</a></p></details>
<ScienceQuiz questions={[{question:'מנוע קיבל 1,000 J ונצילותו 20%. כמה עבודה הפיק?',options:['200 J','800 J','1,000 J'],answer:0,explanation:'W = ηQ = 0.2 × 1000 = 200 J. שאר 800 J נפלטים כחום.'},{question:'למה מחובר למודל גם מקור קר?',options:['כדי לבטל את הכבידה','כי מנוע חום מחזורי פולט אליו חלק מהחום','כדי להפוך את כל החום לעבודה'],answer:1,explanation:'מנוע חום מחזורי אינו ממיר את כל החום שנקלט לעבודה; יש פליטת חום למקור קר.'},{question:'אנרגיית הסיבוב גדלה פי 4, ומומנט ההתמד נשאר קבוע. מה קורה למהירות הזוויתית?',options:['גדלה פי 4','אינה משתנה','גדלה פי 2'],answer:2,explanation:'E = ½Iω², ולכן המהירות הזוויתית יחסית לשורש האנרגיה.'}]}/></>;
}


